### ISSUE TITLE
Hangs several times due to not unlocked tables

### ISSUE THREAD

**Issue by ScreamingDev** [EcomDev/EcomDev_PHPUnit#142]
I have the fixture

```
eav:
  catalog_product:
    - entity_id: 1
      type_id: simple
      sku: ps4
      website_ids:
        - base
      price: 12.99
      status: 1 # Enabled
      visibility: 4 # Catalog & Search
```

And a dispatch like this

```
$route = 'catalog/product/view';
        $this->dispatch($route, array('_store' => 'default', 'id' => 1));
```

Every time the test fails due to lock timeout if I do not UNLOCK TABLES during the test several times.
