### ISSUE TITLE
Fixture for inserting DB records in the customer_entity_int table

### ISSUE THREAD

**Issue by Srikanth-AD** [EcomDev/EcomDev_PHPUnit#201]
As part of a fixture, I am trying to insert a few records in the customer_entity_int table so that I can set the value for a customer EAV attribute for a list of customers.

Could you please provide any example for such a fixture's YAML file?

I have tried the following:

``` yaml
eav:
   customer:
       entity_int:
        - value_id: 22
          entity_type_id: 1
          attribute_id: 241
          entity_id: 7425
          value: 1
```

Error message: Entity Id should be specified in EAV fixture in EcomDev/PHPUnit/Model/Mysql4/Fixture/Eav/Abstract.php on line 144

I have also tried:
tables:
 customer/entity_int

Thanks!
