### ISSUE TITLE
Prevent default scopes from deletion by fixture

### ISSUE THREAD

**Issue by barbazul** [EcomDev/EcomDev_PHPUnit#244]
I just run into an issue where a controller test could not call the dispatch method because it caused  "Cannot run controller test, because the host is not set for base url." even thought the environment was properly set up with base URL and all.

When looking at each test running in isolation in a freshly created test environment each time (that took quite a while) I found that in 2 tests the default Website, Store Group and Store where being deleted.

The culprit was the fixture on each of those tests included the following:

``` yaml
scope:
  website:
    - website_id: 1
      code: main
      name: Main Website
      default_group_id: 1
  group:
    - group_id: 1
      website_id: 1
      name: Main Website Store
      root_category_id: 8
      default_store_id: 1
  store:
    - store_id: 1
      code: default
      website_id: 1
      group_id: 1
      name: Default Store View
      is_active: 1
```

and if you look at the way the cleanup is being done after the run in `EcomDev_PHPUnit_Model_Fixture_Processor_Scope::discard()`

``` php
        [...]
        $scope = array_reverse($fixture->getStorageData(self::STORAGE_KEY));
        foreach ($scope as $models) {
            foreach ($models as $model) {
                $model->delete();
            }
        }
        [...]
```

To make matters worse this was not detected during initial development as the controller tests came from a different dev than the ones with the scope fixtures, so only during the integration of different branches did the problem show up.

I think the discard method should protect the default scopes, probably reverting them to the default status (i.e. default names) to leave the testing environment as if it had been freshly installed.

Another option is to disallow the use of id = 1 for scope fixtures, but that would prevent tests based on having changed the attributes of those scopes (can't imagine why write such tests, but I am not very creative).

@IvanChepurnyi please confirm this issue and I'll go ahead and create a pull request to fix it.
