### ISSUE TITLE
Compatibility magento EE1.13 and EE1.14

### ISSUE THREAD

**Issue by spras** [EcomDev/EcomDev_PHPUnit#253]
Seem to have problem with product fixtures : the stock status is not well indexed and the product isn't available.

**Comment by edi9999** [comment]
I'm able to run tests with products on EE1.13 and EE1.14

Here is my yaml:

```
scope:
  website:
    - website_id: 1
      code: english_website
      name: English Website
      default_group_id: 1
  group:
    - group_id: 1
      website_id: 1
      name: English Store group
      default_store_id: 1
      root_category_id: 1
  store:
    - store_id: 1
      website_id: 1
      group_id: 1
      code: uk
      name: English Store
      is_active: 1
config:
  default/catalog/price/scope: 1
  default/dev/template/allow_symlink: 1
  stores/default/dev/template/allow_symlink: 1
  stores/admin/dev/template/allow_symlink: 1
  stores/french/dev/template/allow_symlink: 1
  stores/german/dev/template/allow_symlink: 1
  websites/admin/dev/template/allow_symlink: 1
  websites/base/dev/template/allow_symlink: 1
  default/carriers/freeshipping/active: 1
  default/payment/fivory/active: 1
  default/payment/fivory/point_of_sale_id: 4444444444
  default/payment/fivory/point_of_sale_key: 4444444444444444444444444444444444444444
eav:
  customer:
    - entity_id: 1
      email: test@netapsys.fr
      password_hash: ''
  catalog_product:
    - entity_id: 1
      type_id: simple
      sku: book
      name: Book
      short_description: Book
      description: Book
      attribute_set_id: 4 # Product entity
      url_key: book
      stock:
        qty: 100.00
        is_in_stock: 1
      website_ids:
        - english_website
      /websites:
        english_website:
          special_price: 7.99
      category_ids:
        - 1 # Default Category
      price: 12.99
      tax_class_id: 2 # Taxable Goods
      status: 1 # Enabled
      visibility: 4 # Visible in Catalog & Search
```
