### ISSUE TITLE
Trouble with fixtures

### ISSUE THREAD

**Issue by amacgregor** [EcomDev/EcomDev_PHPUnit#42]
So I'm trying to setup my fixture for my tests which work with the quote and quote_item objects.  

The error I keep getting is:

```
EcomDev_PHPUnit_Model_Mysql4_Fixture_Exception: Unable to insert/update records for a table "sales/quote_item"

/srv/thirdparty/EcomDev_PHPUnit/app/code/community/EcomDev/PHPUnit/Model/Mysql4/Fixture.php:75
/srv/thirdparty/EcomDev_PHPUnit/app/code/community/EcomDev/PHPUnit/Model/Fixture.php:606
/srv/thirdparty/EcomDev_PHPUnit/app/code/community/EcomDev/PHPUnit/Model/Fixture.php:421
/srv/thirdparty/EcomDev_PHPUnit/app/code/community/EcomDev/PHPUnit/Test/Case.php:803
/srv/extensions/Bogo/development/app/code/local/Demac/Bogo/Test/Model/Observer.php:15

```

My fixture file looks like this:

```

tables:
  sales/quote:
    - entity_id: 1
      is_active: 1
      created_at: 2012-08-17 18:00:41
      updated_at: 2012-08-17 18:00:41
      converted_at: null
      is_virtual: 0
      is_multi_shipping: 0
      items_count: 1
      items_qty: 2.0000
      orig_order_id: 0
      store_to_base_rate: 1.0000
      store_to_quote_rate: 1.0000
      base_currency_code: CAD
      store_currency_code: CAD
      quote_currency_code: CAD
      grand_total: 26.0000
      base_grand_total: 26.0000
      checkout_method: null
      customer_id: null
      customer_tax_class_id: 3
      customer_group_id: 0
      customer_email: null
      customer_prefix: null
      customer_firstname: null
      customer_middlename: null
      customer_lastname: null
      customer_suffix: null
      customer_dob: null
      customer_note: null
      customer_note_notify: 1
      customer_is_guest: 0
      remote_ip: 192.168.0.1
      applied_rule_ids: 12
      reserved_order_id: null
      password_hash: null
      coupon_code: null
      global_currency_code: CAD
      base_to_global_rate: 1.0000
      base_to_quote_rate: 1.0000
      customer_taxvat: null
      customer_gender: null
      subtotal: 26.0000
      base_subtotal: 26.0000
      subtotal_with_discount: 26.0000
      base_subtotal_with_discount: 26.0000
      is_changed: 1
      trigger_recollect: 0
      ext_shipping_info: null
      gift_message_id: null
      is_persistent: 0
      customer_balance_amount_used: 0.0000
      base_customer_bal_amount_used: 0.0000
      use_customer_balance: null
      gift_cards: 'a:0:{}'
      gift_cards_amount: 0.0000
      base_gift_cards_amount: 0.0000
      gift_cards_amount_used: 0.0000
      base_gift_cards_amount_used: 0.0000
      gw_id: null
      gw_allow_gift_receipt: null
      gw_add_card: null
      gw_base_price: 0.0000
      gw_price: 0.0000
      gw_items_base_price: 0.0000
      gw_items_price: 0.0000
      gw_card_base_price: 0.0000
      gw_card_price: 0.0000
      gw_base_tax_amount: 0.0000
      gw_tax_amount: 0.0000
      gw_items_base_tax_amount: 0.0000
      gw_items_tax_amount: 0.0000
      gw_card_base_tax_amount: 0.0000
      gw_card_tax_amount: 0.0000
      use_reward_points: null
      reward_points_balance: 0
      base_reward_currency_amount: 0.0000
      reward_currency_amount: 0.0000
      base_customer_balance_amount_used: 0.0000
      gw_add_printed_card: null
      gw_printed_card_base_price: 0.0000
      gw_printed_card_price: 0.0000
      gw_printed_card_base_tax_amount: 0.0000
      gw_printed_card_tax_amount: 0.0000
      customer_is_loyalty_member: null
      customer_join_loyalty_on: null
    - entity_id: 2
    - entity_id: 3
  sales/quote_item:
    - item_id: 1
      quote_id: 1
      product_id: 1
      parent_item_id: null
      is_virtual: 0
      sku: 14156575-XS-9394
      name: LEGGING
      description: null
      applied_rule_ids: 0
      additional_data: null
      free_shipping: 0
      is_qty_decimal: 0
      no_discount: 0
      weight: 0.4000
      qty: 2
      price: 13.0000
      base_price: 13.0000
      custom_price: 10.0000
      discount_percent: 0.0000
      discount_amount: 0.0000
      base_discount_amount: 0.0000
      tax_percent: 0.0000
      tax_amount: 0.0000
      base_tax_amount: 0.0000
      row_total: 20.0000
      base_row_total: 20.0000
      row_total_with_discount: 0.0000
      row_weight: 0.0000
      product_type: configurable
      base_tax_before_discount: null
      tax_before_discount: null
      original_custom_price: 10.0000
      redirect_url: null
      base_cost: null
      price_incl_tax: 13.0000
      base_price_incl_tax: 13.0000
      row_total_incl_tax: 26.0000
      base_row_total_incl_tax: 26.0000
      hidden_tax_amount: null
      base_hidden_tax_amount: null
      gift_message_id: null
      weee_tax_disposition: 0.0000
      weee_tax_row_disposition: 0.0000
      base_weee_tax_disposition: 0.0000
      base_weee_tax_row_disposition: 0.0000
      weee_tax_applied: 'a:0:{}'
      weee_tax_applied_amount: 0.0000
      weee_tax_applied_row_amount: 0.0000
      base_weee_tax_applied_amount: 0.0000
      base_weee_tax_applied_row_amnt: null
      event_id: null
      giftregistry_item_id: null
      gw_id: null
      gw_base_price: null
      gw_price: null
      gw_base_tax_amount: null
      gw_tax_amount: null
  catalog/product:
    - product_id: 1
```

The only way that I made it run was by droping all the tables in the database(forcing to recreate everything from scratch) and running the test.
